default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: localhost
  database: club_membership_development
  username: root
  password:

development:
  <<: *default

test:
  <<: *default
production:
  <<: *default
